# Generated by Django 5.2.15 on 2026-07-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scents", "0002_museumprofile_statuschange"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="externalevent",
            constraint=models.UniqueConstraint(
                fields=("source", "event_id"), name="unique_external_event"
            ),
        ),
    ]
